### ISSUE TITLE
看了tun2socks参数，才知道ipio原来是全局代理程序，并非vpn程序。不过有个问题

### ISSUE THREAD

**Issue by luckypoem** [txthinking/tun2brook#16]
hi.

sudo ./ipio_darwin_amd64 tun2socks  --socks5 vps-public-ip:portnumber-of-socks-server -u myusername --password mypassword

这里，连接的socks-server 是明文传输，只不过进行了用户名／密码认证，这安全吗？

**Comment by txthinking** [comment]
socks5 是明文

https://www.txthinking.com/talks/

tun2brook 基本上可以认为是 Brook GUI 的命令行版本，最初是辅助我调试GUI的
