### ISSUE TITLE
Problem with tun2brook CLI

### ISSUE THREAD

**Issue by RamZy666** [txthinking/tun2brook#23]
Hi I need some help with tun2brook

so I have an SSHtunnel available on my 127.0.0.1 port 8089 and I want to point all my traffic to it,

`root@ramzy:# tun2brook --link socks5://127.0.0.1:8089 --fakeDNS
`

`2022/10/19 03:48:53 missing port in address`

is there any problem with the command i execute ?

**Comment by txthinking** [comment]
```
1. socks5 created by ssh does not support udp
2. brook testsocks5 -s 127.0.0.1:8089
3. tun2brook -l `brook link -s 127.0.0.1:8089 --bypassCIDR4 the_server_ip_to_avoid_loop_lock`
4. tun2brook -l `brook link -s 1.2.3.4:1080`
```

--help

**Comment by RamZy666** [comment]
Thank you for the help but runnig the commands you provided me I still get the
`2022/10/23 21:15:44 missing port in address`

The output of the firts command:
```
Testing UDP: query http3.ooo A on 8.8.8.8:53
2022/10/23 21:17:41 Sent NegotiationRequest: 0x5 0x1 []byte{0x0}
2022/10/23 21:17:41 Got NegotiationReply: 0x5 0x0
2022/10/23 21:17:41 Sent Request: 0x5 0x3 0x0 0x1 []byte{0x7f, 0x0, 0x0, 0x1} []byte{0xdc, 0xf0}
2022/10/23 21:17:41 read tcp 127.0.0.1:56560->127.0.0.1:8089: read: connection reset by peer
```

**Comment by txthinking** [comment]
How to get brook link
https://www.youtube.com/watch?v=HQG6L9uJx4w

Socks5 UDP
https://www.youtube.com/watch?v=OTYWn6xKJOI

And read from here

https://t.me/brookgroup/32953
