### ISSUE TITLE
如何在ios中使用这个，是否可以参考？或者教程之类的

### ISSUE THREAD

**Issue by yongjie0203** [txthinking/tun2brook#25]
我想在ios中使用用来转发流量到socks5服务器，请问下如何操作

**Comment by txthinking** [comment]
Socks5 UDP
https://www.youtube.com/watch?v=OTYWn6xKJOI

https://txthinking.github.io/brook/index_zh.html#%E5%AE%89%E8%A3%85-brook-%E5%9B%BE%E5%BD%A2%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by txthinking** [comment]
https://apps.apple.com/us/app/brook-a-cross-platform-proxy/id1216002642
