### ISSUE TITLE
参数 doNotChangeRouteAndDNS 不生效

### ISSUE THREAD

**Issue by ztj1993** [txthinking/tun2brook#26]
我运行了 `.\tun2brook_windows_amd64.exe --link "..." --doNotChangeRouteAndDNS`，成功创建了虚拟网卡，但是仍然在系统路由中创建了一条 `0.0.0.0          0.0.0.0       172.19.0.1       172.19.0.2      2` 的规则，直接导致了我无法连接网络，我只有把这条规则删除并创建新的规则后，才能正常上网。

我的需求：
北京区域内网网段：192.168.110.0/24
上海区域内网网段：192.168.120.0/24
杭州区域内网网段：192.168.130.0/24

在以上的内网网段中，各搭建一个 brook server，然后在本地电脑通过 tun2brook 创建三个 tun 网卡，并配置内网网段请求到指定的网关中，从而实现代理访问各区域内网。

由于我在上面的区域中并没有公网 IP，我不得不创建一台公网 IP 搭建 frp 将 brook server 转发出来，我测试了 pptp 等各类 VPN 单都无法解决我的需求，brook 是我唯一测试通过的软件，很强大，谢谢！

如果您有好的方案，也欢迎推荐，非常感谢！

**Comment by txthinking** [comment]
> 但是仍然在系统路由中创建了一条 0.0.0.0 0.0.0.0 172.19.0.1 172.19.0.2 2 的规则

不会route 之类，但默认执行了一条netsh，这条会自动添加路由吗

netsh interface ipv4 set address "Ethernet0" static 172.19.0.2 255.255.0.0 172.19.0.1

**Comment by txthinking** [comment]
no response
